### PR TITLE
fix: setNodes api

### LINKED ISSUE #60: integer overflow in setNodes() api
**Description**

got this error when committing a TreeView [here](https://github.com/ChainSafe/ssz-z/blob/19e243fcd3556b763cd2dc3355ac54de64ca0d9c/test/int/type/tree_view.zig#L49)

```
/ssz-z/src/persistent_merkle_tree/Node.zig:738:38: 0x10461469f in setNodes (int)
            for (d_offset..(path_len - 1)) |bit_i| {
                                     ^
/ssz-z/src/ssz/tree_view.zig:60:48: 0x1046136bb in commit (int)
        const new_root = try self.root.setNodes(pool, gindices, nodes);
                                               ^
/ssz-z/src/ssz/tree_view.zig:98:33: 0x104615aeb in commit (int)
            try self.data.commit(self.allocator, self.pool);
                                ^
/ssz-z/test/int/type/tree_view.zig:57:23: 0x10461669b in test.TreeView (int)
    try cp_view.commit();
                      ^
/opt/homebrew/Cellar/zig/0.14.0_2/lib/zig/compiler/test_runner.zig:126:29: 0x1045b8da3 in mainServer (int)
                test_fn.func() catch |err| switch (err) {
                            ^
/opt/homebrew/Cellar/zig/0.14.0_2/lib/zig/compiler/test_runner.zig:60:26: 0x1045b4937 in main (int)
        return mainServer() catch @panic("internal test runner failure");
                         ^
/opt/homebrew/Cellar/zig/0.14.0_2/lib/zig/std/start.zig:647:22: 0x1045b43b3 in main (int)
            root.main();
                     ^
???:?:?: 0x183e92b97 in ??? (???)
???:?:?: 0x0 in ??? (???)
error: while executing test 'type.tree_view.test.TreeView', the following command terminated with signal 6 (expected exited with code 0):
/ssz-z/.zig-cache/o/fca703c057c5dd903d8cc7d84e48e17c/int --seed=0x318b8c8d --cache-dir=/ssz-z/.zig-cache --listen=- 
Build Summary: 2/4 steps succeeded; 1 failed; 24/24 tests passed
test:int transitive failure
└─ run int failure
error: the following build command failed with exit code 1:
/ssz-z/.zig-cache/o/5afe5c4a851db1ab61bb5e737b981063/build /opt/homebrew/Cellar/zig/0.14.0_2/bin/zig /opt/homebrew/Cellar/zig/0.14.0_2/lib/zig /ssz-z /ssz-z/.zig-cache /Users/tuyennguyen/.cache/zig --seed 0x318b8c8d -Z44352eab378b5c6d test:int
```

### PR DESCRIPTION
**Pull request by twoeths**
**Motivation**
- cannot commit TreeView because setNodes() api was broken

**Description**
- add `node_test.zig` to build process
- write new test and reproduce the issue in `persistent-merkle-tree`

Closes #60

### CODE REVIEW

File: src/persistent_merkle_tree/Node.zig [hunk 1]
```diff
@@ -766,7 +766,7 @@ pub const Id = enum(u32) {
             d_offset = if (i == gindices.len - 1)
                 path_len - gindex.pathLen()
             else
-                path_len - @as(Depth, @intCast(@ctz(@intFromEnum(gindex) ^ @intFromEnum(gindices[i + 1]))));
+                path_len - @as(Depth, @intCast(@bitSizeOf(usize) - @clz(@intFromEnum(gindex) ^ @intFromEnum(gindices[i + 1]))));
```
Comment (twoeths) [inline src/persistent_merkle_tree/Node.zig:769]: the main fix, same to `setNodesAtDepth()`
